# Generated by Django 4.1.2 on 2024-08-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputdata',
            name='category',
        ),
    ]
