# Generated by Django 4.1.2 on 2024-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_outputdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputdata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
